#!/usr/bin/env bash
# Render ~/.openclaw/openclaw.json and ~/.openclaw/.env.
# Two endpoints: OU LiteLLM Sandbox (first choice, if you have a key) and
# OpenRouter (your own key). The default model points at whichever endpoint
# preflight validated (or, before preflight has run, whichever key is present —
# LiteLLM preferred). Override with OPENCLAW_PROVIDER=litellm|openrouter.
# Usage: scripts/configure.sh [OPENROUTER_API_KEY]
#   Key is resolved as: $1  >  env vars  >  existing ~/.openclaw/.env
# Idempotent: safe to run as many times as you like.
set -euo pipefail

# ---- Settings (override via env if your model/endpoint differ) ----
# Default OpenRouter model slug (cheap open model for routine agent loops).
# Verify the current slug at https://openrouter.ai/models before the term.
OPENCLAW_MODEL="${OPENCLAW_MODEL:-qwen/qwen3-coder}"
# Optional comma-separated fallback (secondary) model slugs (same provider).
OPENCLAW_MODEL_FALLBACKS="${OPENCLAW_MODEL_FALLBACKS:-}"
# OU LiteLLM Sandbox endpoint (first choice when you have a key).
LITELLM_BASE_URL="${LITELLM_BASE_URL:-https://litellm.lib.ou.edu}"
# NOTE: the id must match what the gateway reports at /v1/models — for
# this model that's the literal string "Qwen3 Coder 30B", spaces included.
LITELLM_MODEL="${LITELLM_MODEL:-Qwen3 Coder 30B}"
LITELLM_MODEL_NAME="${LITELLM_MODEL_NAME:-Qwen3 Coder 30B (OU LiteLLM)}"
# -----------------------------------------------------------------

STATE_DIR="${HOME}/.openclaw"
CONFIG_FILE="${STATE_DIR}/openclaw.json"
ENV_FILE="${STATE_DIR}/.env"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEMPLATE="${REPO_DIR}/config/openclaw.template.json5"
OR_PLACEHOLDER="sk-or-REPLACE_ME"
LL_PLACEHOLDER="sk-REPLACE_ME"

mkdir -p "${STATE_DIR}"

# Make 'openclaw' findable for the optional validation step below.
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_env.sh"

# Resolve the OpenRouter key: explicit arg > env var > existing .env file.
OR_KEY="${1:-${OPENROUTER_API_KEY:-}}"
if [[ -z "${OR_KEY}" && -f "${ENV_FILE}" ]]; then
  OR_KEY="$(grep -E '^OPENROUTER_API_KEY=' "${ENV_FILE}" | tail -n1 | cut -d= -f2- || true)"
fi
[[ -z "${OR_KEY}" ]] && OR_KEY="${OR_PLACEHOLDER}"

# Optional OU LiteLLM (backup) key — env var > existing .env file > placeholder.
LL_KEY="${LITELLM_API_KEY:-}"
if [[ -z "${LL_KEY}" && -f "${ENV_FILE}" ]]; then
  LL_KEY="$(grep -E '^LITELLM_API_KEY=' "${ENV_FILE}" | tail -n1 | cut -d= -f2- || true)"
fi
[[ -z "${LL_KEY}" ]] && LL_KEY="${LL_PLACEHOLDER}"

# Resolve/persist a gateway client-auth token. Even on loopback the gateway
# authenticates clients (the TUI), so we keep a stable per-Codespace token.
GW_TOKEN=""
[[ -f "${ENV_FILE}" ]] && GW_TOKEN="$(grep -E '^OPENCLAW_GATEWAY_TOKEN=' "${ENV_FILE}" | tail -n1 | cut -d= -f2- || true)"
[[ -z "${GW_TOKEN}" ]] && GW_TOKEN="${OPENCLAW_GATEWAY_TOKEN:-}"
[[ -z "${GW_TOKEN}" ]] && GW_TOKEN="$(openssl rand -hex 24 2>/dev/null || (head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n'))"

# Write ~/.openclaw/.env (OpenClaw reads this as a global env fallback).
umask 077
{
  printf '# Auto-generated by openclaw-codespace-starter. Do NOT commit.\n'
  printf 'OPENROUTER_API_KEY=%s\n' "${OR_KEY}"
  printf 'LITELLM_API_KEY=%s\n' "${LL_KEY}"
  printf 'OPENCLAW_GATEWAY_TOKEN=%s\n' "${GW_TOKEN}"
} > "${ENV_FILE}"
chmod 600 "${ENV_FILE}"

# Which endpoint should the default model use?
# OPENCLAW_PROVIDER env > preflight's ~/.openclaw/.provider > key presence
# (LiteLLM preferred — it's the course's first choice).
PROVIDER="${OPENCLAW_PROVIDER:-}"
if [[ -z "${PROVIDER}" && -f "${STATE_DIR}/.provider" ]]; then
  PROVIDER="$(cat "${STATE_DIR}/.provider" 2>/dev/null || true)"
fi
if [[ -z "${PROVIDER}" ]]; then
  if [[ "${LL_KEY}" != "${LL_PLACEHOLDER}" ]]; then PROVIDER="litellm"; else PROVIDER="openrouter"; fi
fi

# Build the model block: chosen provider's primary + optional fallbacks.
if [[ "${PROVIDER}" == "litellm" ]]; then
  PRIMARY_SLUG="litellm/${LITELLM_MODEL}"
else
  PRIMARY_SLUG="openrouter/${OPENCLAW_MODEL}"
fi
MODEL_BLOCK="{ primary: \"${PRIMARY_SLUG}\""
if [[ -n "${OPENCLAW_MODEL_FALLBACKS}" ]]; then
  fb=""
  IFS=',' read -ra _fbs <<< "${OPENCLAW_MODEL_FALLBACKS}"
  for f in "${_fbs[@]}"; do
    f="${f// /}"; [[ -z "${f}" ]] && continue
    fb="${fb:+${fb}, }\"${PROVIDER}/${f}\""
  done
  [[ -n "${fb}" ]] && MODEL_BLOCK="${MODEL_BLOCK}, fallbacks: [${fb}]"
fi
MODEL_BLOCK="${MODEL_BLOCK} }"

# Render the config from the template.
sed -e "s#@@BASE_URL@@#${LITELLM_BASE_URL}#g" \
    -e "s#@@MODEL_ID@@#${LITELLM_MODEL}#g" \
    -e "s#@@MODEL_NAME@@#${LITELLM_MODEL_NAME}#g" \
    -e "s#@@MODEL_BLOCK@@#${MODEL_BLOCK}#g" \
    "${TEMPLATE}" > "${CONFIG_FILE}"

echo "Wrote ${CONFIG_FILE} (default model: ${PRIMARY_SLUG}; LiteLLM gateway: ${LITELLM_BASE_URL})"

if [[ "${OR_KEY}" == "${OR_PLACEHOLDER}" && "${LL_KEY}" == "${LL_PLACEHOLDER}" ]]; then
  echo "!! No endpoint key found — wrote placeholders."
  echo "   Provide your OU LiteLLM Sandbox key (issued by the course), or create your"
  echo "   own OpenRouter key at https://openrouter.ai (Settings → Keys). Then run"
  echo "   'bash scripts/set-key.sh' or set the matching Codespaces secret."
fi

# Best-effort validation if OpenClaw is already installed.
if command -v openclaw >/dev/null 2>&1; then
  openclaw config validate >/dev/null 2>&1 \
    && echo "Config validated OK." \
    || echo "(Heads up: 'openclaw config validate' reported issues — run 'openclaw doctor' to inspect.)"
fi
